name: Build on Push
on:
  push:
    branches:
      - trunk
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - run: pnpm install --frozen-lockfile
      - run: npm run build --if-present
